defaults: &defaults #working_directory: ./circleci
 docker:
   - image: circleci/node:8.12.0

version: 2
jobs:
 prepare:
   <<: *defaults
   steps:
     - checkout
     # Download and cache dependencies
     - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json" }}
     - run:
         name: install dependancies
         command: yarn
     - save_cache:
         paths:
           - node_modules
           - .cache/Cypress
         key: v1-dependencies-{{ checksum "package.json" }}
     - persist_to_workspace:
         root: .
         paths:
           - node_modules

 build:
   <<: *defaults
   steps:
     - checkout
     - setup_remote_docker
     - attach_workspace:
         at: .
     - run:
         name: Setup common environment variables
         command: |
           echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
           echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
     # I don't know why you have the update npm below?
     - run:
         name: Update npm
         command: 'sudo npm install -g npm@latest'
     - run:
         name: Build image
         command: docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/my-react-app:$CIRCLE_BUILD_NUM .
     - run:
         name: Save image to an archive
         command: |
           mkdir docker-image
           docker save -o docker-image/image.tar ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/my-react-app:$CIRCLE_BUILD_NUM
     - persist_to_workspace:
         root: .
         paths:
           - docker-image
 deploy:
   <<: *defaults
   environment:
     AWS_DEFAULT_OUTPUT: json
   steps:
     - checkout
     - setup_remote_docker
     - attach_workspace:
         at: workspace
     - run:
         name: Load image
         command: |
           docker load --input workspace/docker-image/image.tar
     - run:
         name: Install Dependencies
         working_directory: /
         command: |
           sudo apt-get -y -qq update
           sudo apt-get -y -qq install python3-pip
           sudo pip3 install awscli --upgrade
     - run:
         name: Deploy to Dev
         command: |
           chmod a+x deploy.sh
           ./deploy.sh    
workflows:
  version: 2
  build_deploy:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
            # change the below to the branch you want to deploy
              only: test
            tags:
              only: /.*/