version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage
            ./cc-test-reporter after-build --exit-code $?
  docker:
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker build -t my-react-app .
            docker run -d --name my-react-app my-react-app              

worflows:
  version: 2
  build-deploy: 
    jobs:
      - build
      - test
      - docker:
          requires:
            - build 
            - test
